### ISSUE TITLE
What do we need to do for Alignment case?

### ISSUE THREAD

**Issue by joshuaoreilly** [CMM-22/a3#11]
The instructions for this sub-question of Part III confuses me.

> n addition to moving toward the average position of neighboring birds, each bird now also wants to match the average direction of the others

What does that mean, "match the direction"?

> Using the same averaging principle as in the previous task, define and
implement a force-based formulation to model this velocity alignment behavior.

So we're averaging the velocity direction of all neighbors and moving in that direction? In which case, the boid can't really move in the same direction as the average position of the neighbors as well, right? Those instructions seem contradictory.

**Comment by liyuesolo** [comment]
sorry for the confusion, those are meant for separate tasks. when you match the velocity direction you don't have to match the average position. However, since they are really just penalty forces, you could combine them with different weights, if you wish to have them together.
