### ISSUE TITLE
How to modify frame-rate

### ISSUE THREAD

**Issue by joshuaoreilly** [CMM-22/a3#12]
Using a small step-size results in a super slow moving simulation; I vaguely recall someone commenting in class that the step-size and simulation frame-rate are linked together, but I can't seem to find where in the guiLib code. How can I change the frame-rate so that a smaller step-size doesn't cause the simulation to slow too much?

**Comment by liyuesolo** [comment]
you don't necessarily have to change the frame rate, you could, however, employ different step sizes during one frame refresh.
