### ISSUE TITLE
Encourage circular motion

### ISSUE THREAD

**Issue by Sibsoon** [CMM-22/a3#13]
![image](https://user-images.githubusercontent.com/28922688/162138529-c8711db8-9bc3-402f-aeec-48f1028e275c.png)

From the task description it hits, that we should set the initial velocity to (-yi,xi)^t. Is this a typo and it was meant to be that the initial velocity should be ((xi,yi)^t - circularCenterpoint^t) -> and from this vector (-y,x)^t
Otherwise it seems that the intial velocity is arbitrary to the circular motion, in the worst case it could even directly point towards/away from the center, which then has zero circular motion...

**Comment by liyuesolo** [comment]
you are right, here I wrote _from the origin_ so, the center point you are referring to is just 0,0. but yes the description could do better thanks.

**Comment by Sibsoon** [comment]
I see, thank you for the clarification!
