### ISSUE TITLE
Obstacle types for collision avoidance full points

### ISSUE THREAD

**Issue by azurite** [CMM-22/a3#15]
For the collision avoidance task it states that the boids should steer around an obstacle such as a square or a circle. To get the full points for this task is it enough if we implement this mechanism for only one shape (circle f.ex.) or do we have to support multiple shapes?

Also how should the boids behave if they don't manage to avoid an obstacle? Should we just ignore this case or should we implement some collision handling?

**Comment by liyuesolo** [comment]
Only one shape is enough. You could just implement collision handling by itself, or you could do it together with leader following for example.
