### ISSUE TITLE
How to choose step size?

### ISSUE THREAD

**Issue by AnqiaoLi** [CMM-22/a3#3]
Hi, I'm confused about the meaning of step size. I think the step size in explicit Euler should be the reciprocal of the drawing rate of the application window. Otherwise, the acceleration in visualization will not be the real acceleration. If I am right, why do we need to compare different step sizes?

**Comment by liyuesolo** [comment]
Hi, the step size for the integration schemes is a value that one can vary while the framerate for drawing is a fixed value. 

The framerate is really just how often does the screen refresh. You could for example consider this as your time step or 10 times your step size.

**Comment by AnqiaoLi** [comment]
Thanks! I understand it now.
