### ISSUE TITLE
Collaborative and Adverserial Behavior

### ISSUE THREAD

**Issue by haldunbalim** [CMM-22/a3#7]
Hello,

I have some issues with the description of Collaborative and Adverserial Behavior in the pdf. Let's say there are 6 birds from the same group and 3 birds together from the other group all close enough to each other. Then, depending on simulation order 3 birds can destroy each of these 6 by the rules or vice versa. Similarly, let's say there are 3 birds from the same group close to each other. Since we create bird for each 2-pair of birds will that create 3 birds ((a,b) (a,c) (b,c))?

So, I propose a logic as follows:
We destroy a single bird if there are n birds from the same group and >= n+3 birds from the other group close to it.
We spawn a single bird bird if there are n birds from the other group and >= n+2 birds from the other group

Do you think it is more appropriate? If not could you clarify a bit how these rules should be implemented?

**Comment by liyuesolo** [comment]
Yeah, that's more appropriate, the write-up is more like something you could draw ideas from rather than specific requirements, feel free to implement your own strategies. I'm sure that's much better.

**Comment by samibouziri** [comment]
can we add a loading time to limit the spawn rate? like if two boids spawned a third they can not give birth to another boid before a certain time.

**Comment by liyuesolo** [comment]
sure, of course you can
